apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::212003636274:role/eksctl-simple-jwt-Api-nodegroup-n-NodeInstanceRole-1UIOCKFCHHWOZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::212003636274:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-29T11:19:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8669"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fbb4dfc2-49c8-4add-9b23-827b0e0136ef
